### PR TITLE
Internal Improvements

### PR DESCRIPTION
**Pull request by bebehei**
Hi @VGoshev 

Here are some internal improvements at the code. I'll continue to make PRs on your repo. I need a seafile docker container, but the official seafile container is just crap (eg. haiwen/seafile-docker#25)

Explanation of commits:

- Export PATH and inherit it to childs
    - PATH should be exported to prevent weird errors when ProgramA finds the executable, but ProgramB not.
- apk related changes:
    - split the list into multiple lines and sort the packagelist (see the [docker best practices](https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/#minimize-the-number-of-layers))
    - Move the base packages into a separate layer. Although it is more common to have as less layers as possible, there are actually more pros than cons for it. (rebuild is much faster because of caching).
- Export and define variables in one line
    - Small change for readability
- Remove commented code
    - It's an anti-pattern commenting code and checking it into git, as git already has it in its history.
- the `trap KILL` is effectively dead code, as the `KILL`-signal can't get catched.
- the backticks are not neccessary and actually execute the code returned from grep. But this is not necessary, as grep states in its exit code if it had a match or not.

### CODE REVIEW

**Comment by bebehei** [comment]
It turns out this got quite big. Sorry for this. Also I'm now including the two commits from #8 to resolve merge conflicts.

I hope this improves code quality and gives a better basement for forthcoming PRs.

**Comment by bebehei** [comment]
ping @VGoshev

**Comment by bebehei** [comment]
I decided to give up on Seafile. It's simply not possible to dockerize it properly and split the seahub program from the data and configuration.

Last weekend, I developed this container further outside of this PR. I progressed so far, that I already ported all `build.sh` instructions into a clean Dockerfile, but I never ever could get over that seahub constraint. I'm forced to say, this is shit and I have to blame the seafile devs for it.

Researching this topic in the GitHub bugtrackers revealed many more bad things and habits of seafile, that I even decided to drop it.

I'll close this PR, but KIM these commits are still valid and are able to get cherry picked.

**Comment by Bersam** [comment]
@bebehei any other alternative?

**Comment by bebehei** [comment]
@Bersam What do you mean? Docker container alternative for seafile or cloud storage alternative?

**Comment by Bersam** [comment]
@bebehei alternative cloud storage, i'm using seafile for a while, users are happy with it but i'm stuck at migrating it to another server.

**Comment by Bersam** [comment]
@bebehei alternative cloud storage, i'm using seafile for a while, users are happy with it but i'm stuck at migrating it to another server.

**Comment by bebehei** [comment]
@bersam If you have others non-technical users, have a look at owncloud/nextcloud. I'll probably personally go for syncthing.

I had been in the same situation. I had seafile installed in a KVM Virtual Machine on Ubuntu and had to move it. Therefore I needed to dockerize it. My solution was to put the whole VM into a container. I have to blame myself, but it's the best workaround to have it ported. With a few tweaks the image also is less than two gigs big. I also consider this ["temporary" 😉 ](https://pbs.twimg.com/media/Ce-B2sgXEAAqTQ_.jpg:large).

If you need some files, to get the image working, I could put them into a gist.

**Pull request closed without merging**
